(defun write-string-stream ()
  (defparameter foo (make-string-output-stream))
  (princ "This will go into foo. " foo)
  (princ "This will also go into foo. " foo)
  (get-output-stream-string foo))

(defun with-output-to-string-sample ()
  (with-output-to-string (*standard-output*)
    (princ "the sum of ")
    (princ 5)
    (princ " and ")
    (princ 2)
    (princ " is ")
    (princ (+ 2 5))))
